version: '3'

services:
  paper:
    build:
      context: ./docker/papermc
      args:
        - JDK_VER=17
        - DIST=papermc
        - VERSION=1.20.1
        - BUILD=45
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - "mc-data:/dist/server"
    command: >
      sh -c "echo 'eula=true' > eula.txt &&
        echo 'difficulty=peaceful' >> server.properties &&
        echo 'gamemode=creative' >> server.properties &&
        java -server -Xms2048M -Xmx2048M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=30 -XX:G1HeapRegionSize=32M -jar ../server.jar nogui"

  collector:
    build:
      context: .
      dockerfile: ./docker/collector/Dockerfile
    # image: mc-advancement-collector:v1.0.0
    ports:
      - "18080:18080"
    volumes:
      - "mc-data:/mcroot"
      - "./config:/build/config"
      - "./lang:/build/lang"
      - "./log:/build/log"

volumes:
  mc-data:
    driver: local
